pygments: true
permalink: /otter-pop/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
<<<<<<< HEAD
name: 
description: 
url: http://allievice.com
=======
name: "Otter Pop"
description: "The world's greated jekyll theme"
url: http://tybenz.com/otter-pop
>>>>>>> tybenz/gh-pages
